[settings.python]
uv_venv_auto = true

[tools]
python = "3.10.18"
uv = "0.8.13"
ruff = "0.12.10"
bun = "1.2.21"

[tasks.install]
description = "Install all workspace packages and dependencies from uv.lock"
alias = "i"
run = "uv sync --all-packages"

[tasks.fix]
description = "Lint & format all .py files"
alias = "f"
run = [
    "uv run ruff format .",
    "uv run ruff check . --fix --unsafe-fixes",
]

[tasks.check]
description = "Check for linting and formatting errors without fixing"
alias = "c"
run = [
    "uv run ruff format . --check",
    "uv run ruff check .",
]

[tasks.mypy]
description = "Type check the entire codebase with mypy"
alias = "m"
run = "uv run mypy ."

[tasks.cli]
description = "Run the CLI application with default arguments"
# usage example: `mise run cli -- --debug`
run = "uv run run-analysis -- {{args}}"

[tasks.api]
description = "Start the FastAPI development server"
run = "uv run uvicorn equity_analyzer_api.main:app --reload --app-dir ./packages/api/"

# [tasks.web]
# description = "Start the Bun/Astro development server for the web frontend"
# run = "bun --cwd ./web dev"
